#lang racket

(define (make-account balance password)
  (define (withdraw amount)          
    (if (>= balance amount)
        (begin (set! balance (- balance amount)) balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (make-joint new acc new-pass existing-pass) 1)
  (define (dispatch pass m)
    (cond ((eq? m 'auth) (lambda () (eq? pass password)))
          ((not (eq? pass password)) (lambda (arg) "Wrong password"))
          ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown call -- MAKE-ACCOUNT"
                       m))))
  dispatch)

(define (make-join acc old-pass new-pass)
  (define (withdraw amount) ((acc old-pass 'withdraw) amount))
  (define (deposit amount) ((acc old-pass 'deposit) amount))
  (define (dispatch pass m)
    (cond ((not (eq? pass new-pass)) (lambda (arg) "Wrong password"))
          ((eq? m 'withdraw) withdraw)
          ((eq? m 'deposit) deposit)
          (else (error "Unknown call -- MAKE-JOIN" m))))
  dispatch)

(define acc (make-account 10 'my-pass))
((acc 'my-pass 'withdraw) 5)
((acc 'my-1pass 'withdraw) 5)
(define paul-acc (make-join acc 'my-pass 'new-pass))
((paul-acc 'new-pass 'deposit) 10)
((paul-acc 'wrong-pass 'deposit) 10)
